// Objective-C API for talking to github.com/SummerCash/go-summercash/mobile Go package.
//   gobind -lang=objc github.com/SummerCash/go-summercash/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Run starts a new mobile client, with RPC enabled.
 */
FOUNDATION_EXPORT void MobileRun(void);

#endif
