// Objective-C API for talking to github.com/SummerCash/go-summercash/config Go package.
//   gobind -lang=objc github.com/SummerCash/go-summercash/config
//
// File is generated by gobind. Do not edit.

#ifndef __Config_H__
#define __Config_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ConfigChainConfig;

/**
 * ChainConfig - chain configuration
 */
@interface ConfigChainConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewChainConfig - generate new ChainConfig from genesis.json file
 */
- (nullable instancetype)init:(NSString* _Nullable)genesisFilePath;
// skipped field ChainConfig.Alloc with unsupported type: map[string]*math/big.Float

// skipped field ChainConfig.AllocAddresses with unsupported type: []github.com/SummerCash/go-summercash/common.Address

@property (nonatomic) double inflationRate;
// skipped field ChainConfig.NetworkID with unsupported type: uint

// skipped field ChainConfig.ChainID with unsupported type: github.com/SummerCash/go-summercash/common.Hash

@property (nonatomic) NSString* _Nonnull chainVersion;
/**
 * Bytes - convert given chainConfig to byte array
 */
- (NSData* _Nullable)bytes;
/**
 * String - convert given chainConfig to string
 */
- (NSString* _Nonnull)string;
/**
 * UpdateChainVersion updates the version of the given chain config.
 */
- (BOOL)updateChainVersion:(NSError* _Nullable* _Nullable)error;
/**
 * WriteToMemory - write given chainConfig to memory
 */
- (BOOL)writeToMemory:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Version - dist version def
 */
FOUNDATION_EXPORT NSString* _Nonnull const ConfigVersion;

/**
 * FromBytes - decode byte array into chain config
 */
FOUNDATION_EXPORT ConfigChainConfig* _Nullable ConfigFromBytes(NSData* _Nullable b, NSError* _Nullable* _Nullable error);

/**
 * HandleReceivedConfigRequest - handle config request
 */
FOUNDATION_EXPORT NSData* _Nullable ConfigHandleReceivedConfigRequest(NSError* _Nullable* _Nullable error);

/**
 * NewChainConfig - generate new ChainConfig from genesis.json file
 */
FOUNDATION_EXPORT ConfigChainConfig* _Nullable ConfigNewChainConfig(NSString* _Nullable genesisFilePath, NSError* _Nullable* _Nullable error);

/**
 * ReadChainConfigFromMemory - read chain configuration from chain config json file
 */
FOUNDATION_EXPORT ConfigChainConfig* _Nullable ConfigReadChainConfigFromMemory(NSError* _Nullable* _Nullable error);

#endif
