
// Objective-C API for talking to the following Go packages
//
//	github.com/SummerCash/go-summercash/config
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Config_FRAMEWORK_H__
#define __Config_FRAMEWORK_H__

#include "Config.objc.h"
#include "Universe.objc.h"

#endif
